#!/bin/sh

exec 2>&1
exec setpriv --reuid _shadowsocks --regid _shadowsocks --clear-groups \
	--ambient-caps -all,+net_bind_service,+net_admin \
	--inh-caps -all,+net_bind_service,+net_admin \
	--bounding-set -all,+net_bind_service,+net_admin \
	--no-new-privs -- ssservice local -c /etc/shadowsocks-rust/config.json
